version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: pool_db
    environment:
      POSTGRES_DB: pool_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: sql
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres_data: